/*
 * ReportViewer.java
 *
 * Created on September 17, 2006, 11:38 PM
 */

package com.floreantpos.report;

import java.util.Date;

import com.floreantpos.POSConstants;
import com.floreantpos.bo.ui.BackOfficeWindow;
import com.floreantpos.swing.MessageDialog;
import com.floreantpos.ui.dialog.POSMessageDialog;
import com.floreantpos.ui.util.UiUtil;

/**
 *
 * @author MShahriar
 */
public class ReportViewer extends javax.swing.JPanel {
  /**
   * 
   */
  private static final long serialVersionUID = 1L;
  private Report report;

  /** Creates new form ReportViewer */
  public ReportViewer() {
    initComponents();
  }

  public ReportViewer(Report report) {
    initComponents();

    setReport(report);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents() {
    reportConstraintPanel = new com.floreantpos.swing.TransparentPanel();
    lblStartTime = new javax.swing.JLabel();
    dpStartDate = UiUtil.getCurrentMonthStart();
    dpEndDate = UiUtil.getCurrentMonthEnd();
    lblEndTime = new javax.swing.JLabel();
    btnLoad = new javax.swing.JButton();
    reportPanel = new com.floreantpos.swing.TransparentPanel();

    setLayout(new java.awt.BorderLayout(5, 5));

    lblStartTime.setText(POSConstants.START_DATE + POSConstants.COLON);
    lblEndTime.setText(com.floreantpos.POSConstants.END_DATE + POSConstants.COLON);

    btnLoad.setText(com.floreantpos.POSConstants.LOAD);
    btnLoad.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        doRefreshReport(evt);
      }
    });

    org.jdesktop.layout.GroupLayout reportConstraintPanelLayout =
        new org.jdesktop.layout.GroupLayout(reportConstraintPanel);
    reportConstraintPanel.setLayout(reportConstraintPanelLayout);
    reportConstraintPanelLayout.setHorizontalGroup(
        reportConstraintPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(reportConstraintPanelLayout.createSequentialGroup().addContainerGap()
                .add(reportConstraintPanelLayout
                    .createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(reportConstraintPanelLayout.createSequentialGroup()
                        .add(reportConstraintPanelLayout
                            .createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(lblStartTime))
                        .add(15, 15, 15)
                        .add(reportConstraintPanelLayout
                            .createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(dpStartDate, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(lblEndTime)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(dpEndDate,
                            org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                            org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                            org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(org.jdesktop.layout.GroupLayout.TRAILING, btnLoad)).addContainerGap()));
    reportConstraintPanelLayout.setVerticalGroup(
        reportConstraintPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(reportConstraintPanelLayout.createSequentialGroup().addContainerGap()
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(reportConstraintPanelLayout
                    .createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(dpEndDate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                        org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                        org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblEndTime)
                    .add(reportConstraintPanelLayout.createSequentialGroup()
                        .add(reportConstraintPanelLayout
                            .createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(dpStartDate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
                                org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
                                org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(lblStartTime))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED).add(btnLoad)))
            .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

    reportConstraintPanelLayout.linkSize(
        new java.awt.Component[] {dpEndDate, dpStartDate, lblStartTime, lblEndTime},
        org.jdesktop.layout.GroupLayout.VERTICAL);

    add(reportConstraintPanel, java.awt.BorderLayout.NORTH);

    reportPanel.setLayout(new java.awt.BorderLayout());

    add(reportPanel, java.awt.BorderLayout.CENTER);

  }// </editor-fold>//GEN-END:initComponents

  private void doRefreshReport(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_doRefreshReport
    Date fromDate = dpStartDate.getDate();
    Date toDate = dpEndDate.getDate();

    if (fromDate.after(toDate)) {
      POSMessageDialog.showError(BackOfficeWindow.getInstance(),
          com.floreantpos.POSConstants.FROM_DATE_CANNOT_BE_GREATER_THAN_TO_DATE_);
      return;
    }

    try {
      reportPanel.removeAll();
      reportPanel.revalidate();

      if (report != null) {
        report.setStartDate(fromDate);
        report.setEndDate(toDate);

        report.refresh();

        if (report != null && report.getViewer() != null) {
          reportPanel.add(report.getViewer());
          reportPanel.revalidate();
        }
      }

    } catch (Exception e) {
      MessageDialog.showError(this, com.floreantpos.POSConstants.ERROR_MESSAGE, e);
    }
  }// GEN-LAST:event_doRefreshReport


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnLoad;
  private org.jdesktop.swingx.JXDatePicker dpEndDate;
  private org.jdesktop.swingx.JXDatePicker dpStartDate;
  private javax.swing.JLabel lblStartTime;
  private javax.swing.JLabel lblEndTime;
  private com.floreantpos.swing.TransparentPanel reportConstraintPanel;
  private com.floreantpos.swing.TransparentPanel reportPanel;
  // End of variables declaration//GEN-END:variables

  public Report getReport() {
    return report;
  }

  public void setReport(Report report) {
    this.report = report;
  }

}
